// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview AI tool to suggest learning milestones based on user-defined goals.
 *
 * - suggestLearningMilestones - A function that suggests learning milestones.
 * - SuggestLearningMilestonesInput - The input type for the suggestLearningMilestones function.
 * - SuggestLearningMilestonesOutput - The return type for the suggestLearningMilestones function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestLearningMilestonesInputSchema = z.object({
  goal: z.string().describe('The overall learning goal of the user.'),
  currentSkills: z.string().describe('The current skills of the user.'),
  learningPreferences: z.string().describe('The learning preferences of the user.'),
});

export type SuggestLearningMilestonesInput = z.infer<typeof SuggestLearningMilestonesInputSchema>;

const SuggestLearningMilestonesOutputSchema = z.object({
  milestones: z.array(z.string()).describe('A list of suggested learning milestones.'),
});

export type SuggestLearningMilestonesOutput = z.infer<typeof SuggestLearningMilestonesOutputSchema>;

export async function suggestLearningMilestones(input: SuggestLearningMilestonesInput): Promise<SuggestLearningMilestonesOutput> {
  return suggestLearningMilestonesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestLearningMilestonesPrompt',
  input: {schema: SuggestLearningMilestonesInputSchema},
  output: {schema: SuggestLearningMilestonesOutputSchema},
  prompt: `You are an AI learning assistant. Your goal is to help users achieve their learning goals by suggesting a list of milestones.

  Consider the user's current skills, learning preferences, and overall goal when suggesting milestones.

  Goal: {{{goal}}}
Current Skills: {{{currentSkills}}}
Learning Preferences: {{{learningPreferences}}}

  Suggest a list of milestones to achieve the goal:
  `,
});

const suggestLearningMilestonesFlow = ai.defineFlow(
  {
    name: 'suggestLearningMilestonesFlow',
    inputSchema: SuggestLearningMilestonesInputSchema,
    outputSchema: SuggestLearningMilestonesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
